/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as SelectModuleRouteImport } from './routes/select-module'
import { Route as CustomerGstinRouteImport } from './routes/customer.$gstin'
import { Route as InvoiceIndexRouteImport } from './routes/invoice.index'
import { Route as InvoiceTypeIndexRouteImport } from './routes/invoice.$type.index'
import { Route as InvoiceTypeCompanyRouteImport } from './routes/invoice.$type.$company'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectModuleRoute = SelectModuleRouteImport.update({
  id: '/select-module',
  path: '/select-module',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerGstinRoute = CustomerGstinRouteImport.update({
  id: '/customer/$gstin',
  path: '/customer/$gstin',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIndexRoute = InvoiceIndexRouteImport.update({
  id: '/invoice/',
  path: '/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTypeIndexRoute = InvoiceTypeIndexRouteImport.update({
  id: '/invoice/$type/',
  path: '/invoice/$type/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTypeCompanyRoute = InvoiceTypeCompanyRouteImport.update({
  id: '/invoice/$type/$company',
  path: '/invoice/$type/$company',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-module': typeof SelectModuleRoute
  '/customer/$gstin': typeof CustomerGstinRoute
  '/invoice/': typeof InvoiceIndexRoute
  '/invoice/$type/$company': typeof InvoiceTypeCompanyRoute
  '/invoice/$type/': typeof InvoiceTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-module': typeof SelectModuleRoute
  '/customer/$gstin': typeof CustomerGstinRoute
  '/invoice': typeof InvoiceIndexRoute
  '/invoice/$type/$company': typeof InvoiceTypeCompanyRoute
  '/invoice/$type': typeof InvoiceTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-company': typeof SelectCompanyRoute
  '/select-module': typeof SelectModuleRoute
  '/customer/$gstin': typeof CustomerGstinRoute
  '/invoice/': typeof InvoiceIndexRoute
  '/invoice/$type/$company': typeof InvoiceTypeCompanyRoute
  '/invoice/$type/': typeof InvoiceTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-company'
    | '/select-module'
    | '/customer/$gstin'
    | '/invoice/'
    | '/invoice/$type/$company'
    | '/invoice/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-company'
    | '/select-module'
    | '/customer/$gstin'
    | '/invoice'
    | '/invoice/$type/$company'
    | '/invoice/$type'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/select-company'
    | '/select-module'
    | '/customer/$gstin'
    | '/invoice/'
    | '/invoice/$type/$company'
    | '/invoice/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelectCompanyRoute: typeof SelectCompanyRoute
  SelectModuleRoute: typeof SelectModuleRoute
  CustomerGstinRoute: typeof CustomerGstinRoute
  InvoiceIndexRoute: typeof InvoiceIndexRoute
  InvoiceTypeCompanyRoute: typeof InvoiceTypeCompanyRoute
  InvoiceTypeIndexRoute: typeof InvoiceTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-module': {
      id: '/select-module'
      path: '/select-module'
      fullPath: '/select-module'
      preLoaderRoute: typeof SelectModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$gstin': {
      id: '/customer/$gstin'
      path: '/customer/$gstin'
      fullPath: '/customer/$gstin'
      preLoaderRoute: typeof CustomerGstinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/': {
      id: '/invoice/'
      path: '/invoice'
      fullPath: '/invoice/'
      preLoaderRoute: typeof InvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$type/': {
      id: '/invoice/$type/'
      path: '/invoice/$type'
      fullPath: '/invoice/$type/'
      preLoaderRoute: typeof InvoiceTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$type/$company': {
      id: '/invoice/$type/$company'
      path: '/invoice/$type/$company'
      fullPath: '/invoice/$type/$company'
      preLoaderRoute: typeof InvoiceTypeCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelectCompanyRoute: SelectCompanyRoute,
  SelectModuleRoute: SelectModuleRoute,
  CustomerGstinRoute: CustomerGstinRoute,
  InvoiceIndexRoute: InvoiceIndexRoute,
  InvoiceTypeCompanyRoute: InvoiceTypeCompanyRoute,
  InvoiceTypeIndexRoute: InvoiceTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
